apps/front_end/lib/web/organization_router.ex
defmodule FrontEnd.OrganizationRouter do
  use FrontEnd.Web, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  scope "/verify", FrontEnd.Verification do
    pipe_through(:browser)

    resources("/", VerificationController, only: [:show])
  end
end

apps/front_end/lib/web/router.ex
defmodule FrontEnd.Router do
  use FrontEnd.Web, :router
  use Plug.ErrorHandler

  if Mix.env() == :dev do
    forward("/sent_emails", Bamboo.EmailPreviewPlug)
  end

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)

    if Mix.env() == :prod do
      plug(Plug.SSL, rewrite_on: [:x_forwarded_proto])
      plug(:put_secure_browser_headers)
    end
  end

  pipeline :browser_auth do
    plug(Guardian.Plug.VerifySession)
    plug(Guardian.Plug.LoadResource)
    plug(FrontEnd.Plug.CurrentAccount)
  end

  scope "/", FrontEnd do
    pipe_through([:browser, :browser_auth])

    get("/", PageController, :index)

    get("/docs", DocumentationController, :index)

    resources("/sessions", SessionController, only: [:new, :create, :delete])

    resources(
      "/passwords",
      PasswordController,
      only: [:new, :create, :edit, :update],
      param: "token"
    )
  end

  scope "/app", FrontEnd.App do
    pipe_through([:browser, :browser_auth])

    get("/", DashboardController, :index)

    get("/odd_connect.pub", SigningKeyController, :index)

    get("/accounts/edit", AccountController, :edit, as: :account)
    put("/accounts", AccountController, :update, as: :account)
    put("/accounts/password", AccountController, :password, as: :account)

    get("/accounts/:urn/select", OrganizationAccountController, :select)
    get("/accounts", OrganizationAccountController, :index)

    get("/organizations/:id/switch", OrganizationController, :switch, as: :organization)

    resources(
      "/organizations",
      OrganizationController,
      only: [:edit, :update, :index],
      param: "urn"
    )

    get("/transactions/search", TransactionController, :search, as: :search)
    resources("/transactions", TransactionController, only: [:index, :show])
    resources("/connections", ConnectionController, only: [:index, :show])

    resources(
      "/device_users",
      DeviceUserController,
      only: [:index, :show],
      param: "email",
      as: :app_device_user
    )

    resources(
      "/entitlements",
      EntitlementController,
      only: [:new, :create, :edit, :update, :delete, :index]
    )

    resources(
      "/webhooks",
      WebhookController,
      only: [:new, :create, :edit, :update, :delete, :index]
    )
  end

  defp handle_errors(conn, %{kind: _kind, reason: _reason, stack: _stacktrace}) do
    conn =
      conn
      |> Plug.Conn.fetch_cookies()
      |> Plug.Conn.fetch_query_params()
      |> Plug.Conn.fetch_session()

    %{
      "request" => %{
        "cookies" => conn.req_cookies,
        "url" => "#{conn.scheme}://#{conn.host}:#{conn.port}#{conn.request_path}",
        "user_ip" => conn.remote_ip |> Tuple.to_list() |> Enum.join("."),
        "headers" => Enum.into(conn.req_headers, %{}),
        "session" => conn.private[:plug_session] || %{},
        "params" => conn.params,
        "method" => conn.method
      },
      "server" => %{}
    }
  end
end

apps/front_end/lib/web/controllers/app/webhook_controller.ex
defmodule FrontEnd.App.WebhookController do
  use FrontEnd.Web, :authenticated_browser_controller

  # Make sure that we have a valid token
  # We've aliased Guardian.Plug.EnsureAuthenticated in our
  # FrontEnd.Web.authenticated_browser_controller macro
  plug(EnsureAuthenticated, handler: __MODULE__)
  plug(EnsureResourceType, type: Auth.OrganizationAccount, handler: __MODULE__)
  # Make sure that the token's permissions are valid for the given actions
  # We may not want to use this if we're relying on user.roles, as
  # they can change while the token's permissions will not change
  # plug EnsurePermissions, [handler: __MODULE__, roles: ~w(admin)] when action in [:index, :show, :delete]

  @valid_types Connect.valid_webhook_types()

  def index(conn, params, %{organization: organization}, _claims) do
    webhooks = Connect.list_webhooks(organization, params)

    conn
    |> render("index.html", webhooks: webhooks)
  end

  def new(conn, _params, current_customer, _claims) do
    organization = current_customer.organization
    changeset = Connect.build_webhook(%{organization: organization})

    conn
    |> render(
      "new.html",
      webhook: changeset,
      valid_types: @valid_types,
      organization: organization,
      action: webhook_path(conn, :create),
      method: "post"
    )
  end

  def edit(conn, %{"id" => id}, current_customer, _claims) do
    organization = current_customer.organization
    webhook = check_webhook_belongs_to_organization(id, organization)

    changeset = Connect.build_webhook(webhook)

    conn
    |> render(
      "edit.html",
      webhook: changeset,
      valid_types: @valid_types,
      organization: organization,
      action: webhook_path(conn, :update, id),
      method: "put"
    )
  end

  def create(conn, %{"webhook" => webhook_params}, current_customer, _claims) do
    organization = current_customer.organization
    webhook_params = for {key, val} <- webhook_params, into: %{}, do: {String.to_atom(key), val}
    webhook_params = Map.put(webhook_params, :organization, organization)

    case Connect.create_webhook(%{webhook_params | organization: organization}) do
      {:ok, _webhook} ->
        conn
        |> put_flash(:success, "Successfully created webhook")
        |> redirect(to: webhook_path(conn, :index))

      {:error, changeset} ->
        conn
        |> render(
          "new.html",
          webhook: changeset,
          valid_types: @valid_types,
          organization: organization,
          action: webhook_path(conn, :create),
          method: "post"
        )
    end
  end

  def update(conn, %{"id" => id, "webhook" => webhook_params}, current_customer, _claims) do
    organization = current_customer.organization
    check_webhook_belongs_to_organization(id, organization)

    case Connect.update_webhook(id, webhook_params) do
      {:ok, _webhook} ->
        conn
        |> put_flash(:success, "Successfully updated webhook")
        |> redirect(to: webhook_path(conn, :index))

      {:error, changeset} ->
        conn
        |> put_flash(:error, "Some errors were found.")
        |> render(
          "edit.html",
          webhook: changeset,
          valid_types: @valid_types,
          organization: organization,
          action: webhook_path(conn, :update, id),
          method: "put"
        )
    end
  end

  def delete(conn, %{"id" => id}, current_customer, _claims) do
    organization = current_customer.organization
    check_webhook_belongs_to_organization(id, organization)

    case Connect.delete_webhook(id) do
      {:ok, _} ->
        conn
        |> put_flash(:success, "Successfully removed webhook from #{organization.name}")
        |> redirect(to: webhook_path(conn, :index))

      {:error, changeset} ->
        conn
        |> put_flash(:error, FrontEnd.ErrorHelpers.error_string_from_changeset(changeset))
        |> render(
          "edit.html",
          webhook: changeset,
          valid_types: @valid_types,
          organization: organization,
          action: webhook_path(conn, :update, id),
          method: "put"
        )
    end
  end

  defp check_webhook_belongs_to_organization(id, organization) do
    case Connect.find_webhook(id: id, organization_id: organization.id) do
      nil ->
        raise FrontEnd.NotFound

      webhook ->
        webhook
    end
  end
end

apps/front_end/lib/web/views/app/webhook_view.ex
defmodule FrontEnd.App.WebhookView do
  use FrontEnd.Web, :view
  import Scrivener.HTML
end

apps/front_end/lib/web/templates/app/webhook/edit.html.eex
<div class="container">
	<div class="row">
		<div class="col-lg-12">
			<ol class="breadcrumb">
				<li><%= link "Dashboard", to: dashboard_path(@conn, :index) %></li>
				<li><%= link "Organization Settings", to: organization_path(@conn, :edit, @organization.urn) %></li>
	  		<li class="active">Webhook</li>
			</ol>
		</div>
	</div>

	<div class="row">
		<div class="col-md-6">
			<h3>Editing Webhook for <%= @organization.name %></h3>
			<%= render "form.html", webhook: @webhook, valid_types: @valid_types, action: @action, method: @method %>
		</div>
	</div>
</div>

apps/front_end/lib/web/templates/app/webhook/form.html.eex
<%= form_for @webhook, @action, [as: :webhook, method: @method], fn f -> %>
	<div class="form-group">
		<%= label f, :type, class: "control-label text-uppercase text-muted" %>
		<%= select f, :type, @valid_types, class: "form-control" %>
	</div>
	<%= input f, :url %>
	<%= json_input f, :headers %>

	<%= submit "Submit", class: "btn btn-primary" %>
<% end %>

apps/front_end/lib/web/templates/app/webhook/index.html.eex
<div class="container">
	<div class="row">
		<div class="col-lg-12">
			<h4>Webhooks</h4>
			<p>Organizations can use webhooks to POST data back when certain events occur.</p>
			<table class="table table-condensed table-hover">
				<thead>
					<tr>
						<th>
							<%= link "Create Webhook", to: webhook_path(@conn, :new), class: "btn btn-info btn-sm", role: "button" %>
						</th>
						<th colspan="2" class="text-right">
							<%= display_current_record_set(@webhooks) %>
						</th>
					</tr>
					<tr>
						<th>Type</th>
						<th colspan="2">URL</th>
					</tr>
				</thead>
				<tbody>
					<%= for webhook <- @webhooks do %>
						<tr>
							<td><%= webhook.type %></td>
							<td><%= webhook.url %></td>
							<td class="text-right">
								<%= link "Edit", to: webhook_path(@conn, :edit, webhook.id), class: "btn btn-default btn-sm", role: "button" %>
								<%= link "Delete", to: webhook_path(@conn, :delete, webhook.id), class: "btn btn-danger btn-sm", role: "button", method: "delete", data: [confirm: "Are you sure?"] %>
							</td>
						</tr>
					<% end %>
				</tbody>
				<tfoot>
					<tr>
						<th colspan="3" class="text-right">
							<%= pagination_links @webhooks %>
							<%= display_current_page(@webhooks) %>
						</th>
					</tr>
				</tfoot>
			</table>
		</div>
	</div>
</div>

apps/front_end/lib/web/templates/app/webhook/new.html.eex
<div class="container">
	<div class="row">
		<div class="col-lg-12">
			<ol class="breadcrumb">
				<li><%= link "Dashboard", to: dashboard_path(@conn, :index) %></li>
				<li><%= link "Organization Settings", to: organization_path(@conn, :edit, @organization.id) %></li>
	  		<li class="active">New Webhook</li>
			</ol>
		</div>
	</div>

	<div class="row">
		<div class="col-md-6">
			<h3>New Webhook for <%= @organization.name %></h3>
			<%= render "form.html", webhook: @webhook, valid_types: @valid_types, action: @action, method: @method %>
		</div>
	</div>
</div>