apps/front_end/lib/web/organization_router.ex
defmodule FrontEnd.OrganizationRouter do
  use FrontEnd.Web, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  scope "/verify", FrontEnd.Verification do
    pipe_through(:browser)

    resources("/", VerificationController, only: [:show])
  end
end

apps/front_end/lib/web/router.ex
defmodule FrontEnd.Router do
  use FrontEnd.Web, :router
  use Plug.ErrorHandler

  if Mix.env() == :dev do
    forward("/sent_emails", Bamboo.EmailPreviewPlug)
  end

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)

    if Mix.env() == :prod do
      plug(Plug.SSL, rewrite_on: [:x_forwarded_proto])
      plug(:put_secure_browser_headers)
    end
  end

  pipeline :browser_auth do
    plug(Guardian.Plug.VerifySession)
    plug(Guardian.Plug.LoadResource)
    plug(FrontEnd.Plug.CurrentAccount)
  end

  scope "/", FrontEnd do
    pipe_through([:browser, :browser_auth])

    get("/", PageController, :index)

    get("/docs", DocumentationController, :index)

    resources("/sessions", SessionController, only: [:new, :create, :delete])

    resources(
      "/passwords",
      PasswordController,
      only: [:new, :create, :edit, :update],
      param: "token"
    )
  end

  scope "/app", FrontEnd.App do
    pipe_through([:browser, :browser_auth])

    get("/", DashboardController, :index)

    get("/odd_connect.pub", SigningKeyController, :index)

    get("/accounts/edit", AccountController, :edit, as: :account)
    put("/accounts", AccountController, :update, as: :account)
    put("/accounts/password", AccountController, :password, as: :account)

    get("/accounts/:urn/select", OrganizationAccountController, :select)
    get("/accounts", OrganizationAccountController, :index)

    get("/organizations/:id/switch", OrganizationController, :switch, as: :organization)

    resources(
      "/organizations",
      OrganizationController,
      only: [:edit, :update, :index],
      param: "urn"
    )

    get("/transactions/search", TransactionController, :search, as: :search)
    resources("/transactions", TransactionController, only: [:index, :show])
    resources("/connections", ConnectionController, only: [:index, :show])

    resources(
      "/device_users",
      DeviceUserController,
      only: [:index, :show],
      param: "email",
      as: :app_device_user
    )

    resources(
      "/entitlements",
      EntitlementController,
      only: [:new, :create, :edit, :update, :delete, :index]
    )

    resources(
      "/webhooks",
      WebhookController,
      only: [:new, :create, :edit, :update, :delete, :index]
    )
  end

  defp handle_errors(conn, %{kind: _kind, reason: _reason, stack: _stacktrace}) do
    conn =
      conn
      |> Plug.Conn.fetch_cookies()
      |> Plug.Conn.fetch_query_params()
      |> Plug.Conn.fetch_session()

    %{
      "request" => %{
        "cookies" => conn.req_cookies,
        "url" => "#{conn.scheme}://#{conn.host}:#{conn.port}#{conn.request_path}",
        "user_ip" => conn.remote_ip |> Tuple.to_list() |> Enum.join("."),
        "headers" => Enum.into(conn.req_headers, %{}),
        "session" => conn.private[:plug_session] || %{},
        "params" => conn.params,
        "method" => conn.method
      },
      "server" => %{}
    }
  end
end

apps/front_end/lib/web/views/app/layout_view.ex
defmodule FrontEnd.App.LayoutView do
  use FrontEnd.Web, :view
end

apps/front_end/lib/web/views/layout_view.ex
defmodule FrontEnd.LayoutView do
  use FrontEnd.Web, :view
end

apps/front_end/lib/web/views/verification/layout_view.ex
defmodule FrontEnd.Verification.LayoutView do
  use FrontEnd.Web, :view
end

apps/front_end/lib/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Odd Connect - App</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body data-js-view-name="<%= js_view_name(@conn, @view_template) %>">
		<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Odd Connect</a>
        </div>
				<div id="navbar" class="collapse navbar-collapse navbar-right">
          <ul class="nav navbar-nav">
						<%= if @current_account do %>
							<li><%= link "Documentation", to: documentation_path(@conn, :index), target: "_blank" %></li>
							<li>
								<a href="<%= dashboard_path(@conn, :index) %>">
									<span class="glyphicon glyphicon-log-in" aria-hidden="true"></span> Go To App
								</a>
							</li>
					  <% else %>
							<li><a href="<%= session_path(@conn, :new) %>"><span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>&nbsp;&nbsp;Log In</a></li>
						<% end %>
          </ul>
        </div>
      </div>
    </nav>

		<%= if success = get_flash(@conn, :success) do %>
			<div class="container alert alert-success">
				<p><%= success %></p>
			</div>
		<% end %>
		<%= if info = get_flash(@conn, :info) do %>
			<div class="container alert alert-info">
				<p><%= info %></p>
			</div>
		<% end %>
		<%= if error = get_flash(@conn, :error) do %>
			<div class="container alert alert-danger">
				<p><%= error %></p>
			</div>
		<% end %>
		<%= if warning = get_flash(@conn, :warning) do %>
			<div class="container alert alert-warning">
				<p><%= warning %></p>
			</div>
		<% end %>

    <%= render @view_module, @view_template, assigns %>

    <footer class="footer">
			<div class="container">
				<p class="text-muted">Powered by <a href="http://oddnetworks.com">Odd Networks</a></p>
			</div>
    </footer>

    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>