apps/front_end/lib/web/organization_router.ex
defmodule FrontEnd.OrganizationRouter do
  use FrontEnd.Web, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  scope "/verify", FrontEnd.Verification do
    pipe_through(:browser)

    resources("/", VerificationController, only: [:show])
  end
end

apps/front_end/lib/web/router.ex
defmodule FrontEnd.Router do
  use FrontEnd.Web, :router
  use Plug.ErrorHandler

  if Mix.env() == :dev do
    forward("/sent_emails", Bamboo.EmailPreviewPlug)
  end

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)

    if Mix.env() == :prod do
      plug(Plug.SSL, rewrite_on: [:x_forwarded_proto])
      plug(:put_secure_browser_headers)
    end
  end

  pipeline :browser_auth do
    plug(Guardian.Plug.VerifySession)
    plug(Guardian.Plug.LoadResource)
    plug(FrontEnd.Plug.CurrentAccount)
  end

  scope "/", FrontEnd do
    pipe_through([:browser, :browser_auth])

    get("/", PageController, :index)

    get("/docs", DocumentationController, :index)

    resources("/sessions", SessionController, only: [:new, :create, :delete])

    resources(
      "/passwords",
      PasswordController,
      only: [:new, :create, :edit, :update],
      param: "token"
    )
  end

  scope "/app", FrontEnd.App do
    pipe_through([:browser, :browser_auth])

    get("/", DashboardController, :index)

    get("/odd_connect.pub", SigningKeyController, :index)

    get("/accounts/edit", AccountController, :edit, as: :account)
    put("/accounts", AccountController, :update, as: :account)
    put("/accounts/password", AccountController, :password, as: :account)

    get("/accounts/:urn/select", OrganizationAccountController, :select)
    get("/accounts", OrganizationAccountController, :index)

    get("/organizations/:id/switch", OrganizationController, :switch, as: :organization)

    resources(
      "/organizations",
      OrganizationController,
      only: [:edit, :update, :index],
      param: "urn"
    )

    get("/transactions/search", TransactionController, :search, as: :search)
    resources("/transactions", TransactionController, only: [:index, :show])
    resources("/connections", ConnectionController, only: [:index, :show])

    resources(
      "/device_users",
      DeviceUserController,
      only: [:index, :show],
      param: "email",
      as: :app_device_user
    )

    resources(
      "/entitlements",
      EntitlementController,
      only: [:new, :create, :edit, :update, :delete, :index]
    )

    resources(
      "/webhooks",
      WebhookController,
      only: [:new, :create, :edit, :update, :delete, :index]
    )
  end

  defp handle_errors(conn, %{kind: _kind, reason: _reason, stack: _stacktrace}) do
    conn =
      conn
      |> Plug.Conn.fetch_cookies()
      |> Plug.Conn.fetch_query_params()
      |> Plug.Conn.fetch_session()

    %{
      "request" => %{
        "cookies" => conn.req_cookies,
        "url" => "#{conn.scheme}://#{conn.host}:#{conn.port}#{conn.request_path}",
        "user_ip" => conn.remote_ip |> Tuple.to_list() |> Enum.join("."),
        "headers" => Enum.into(conn.req_headers, %{}),
        "session" => conn.private[:plug_session] || %{},
        "params" => conn.params,
        "method" => conn.method
      },
      "server" => %{}
    }
  end
end

apps/front_end/lib/web/controllers/app/organization_controller.ex
defmodule FrontEnd.App.OrganizationController do
  use FrontEnd.Web, :authenticated_browser_controller

  plug(EnsureAuthenticated, handler: __MODULE__)
  plug(EnsureResourceType, type: Auth.OrganizationAccount, handler: __MODULE__)

  def index(conn, _params, %{account: %{is_admin: true}}, _claims) do
    organizations = Connect.list_organizations()

    conn
    |> render("index.html", organizations: organizations)
  end
  def index(conn, _params, %{account: account}, _claims) do
    organizations = Connect.list_organizations_for_account(account)

    # TODO - when organizations length == 1 just switch to that org
    conn
    |> render("index.html", organizations: organizations)
  end

  def switch(
        conn,
        %{"id" => id},
        %{account: %{id: account_id, is_admin: true}},
        _claims
      ) do
    Auth.find_organization_account(account_id, id, nil)
    |> complete_switch(conn)
  end

  def edit(conn, %{"urn" => urn}, current_account, _claims) do
    organization =
      current_account
      |> check_organization_access(urn)
      |> load_organization(urn)

    conn
    |> render(
      "edit.html",
      action: organization_path(conn, :update, urn),
      organization: Connect.edit_organization(organization),
      webhooks: organization.webhooks,
      entitlements: organization.entitlements
    )
  end

  def update(
        conn,
        %{"urn" => urn, "organization" => organization_params},
        current_account,
        _claims
      ) do
    organization =
      current_account
      |> check_organization_access(urn)
      |> load_organization(urn)

    case Connect.update_organization(urn, organization_params) do
      {:ok, organization} ->
        conn
        |> put_flash(:success, "Successfully updated #{organization.name}")
        |> redirect(to: organization_path(conn, :edit, organization.urn))

      {:error, changeset} ->
        changeset = %{changeset | action: :organization}

        conn
        |> render(
          "edit.html",
          action: organization_path(conn, :update, urn),
          organization: changeset,
          webhooks: organization.webhooks,
          entitlements: organization.entitlements
        )
    end
  end

  defp check_organization_access(%{permissions: :admin}, _id), do: true
  defp check_organization_access(%{organization: %{urn: urn}}, urn), do: true
  defp check_organization_access(_, _), do: false

  defp load_organization(_has_access = true, urn) do
    case Connect.find_organization(urn: urn) do
      nil -> raise FrontEnd.NotFound
      org -> org
    end
  end

  defp load_organization(_does_not_have_access, _), do: raise(FrontEnd.NotFound)

  defp complete_switch({:ok, organization_account}, conn) do
    conn
    |> Guardian.Plug.sign_in(organization_account)
    |> put_flash(:success, "You have successfully switched accounts")
    |> redirect(to: dashboard_path(conn, :index))
  end

  defp complete_switch(_unsuccessful, conn) do
    conn
    |> put_flash(:info, "Unable to switch accounts")
    |> redirect(to: dashboard_path(conn, :index))
  end
end

apps/front_end/lib/web/views/app/organization_view.ex
defmodule FrontEnd.App.OrganizationView do
  use FrontEnd.Web, :view

  alias Connect.Organization

  def device_connection_email_template_fields do
    Organization.Email.device_connection_email_fields()
    |> Enum.map(fn field ->
      "<code>{{#{field}}}</code>"
    end)
    |> Enum.join(", ")
  end
end

apps/front_end/lib/web/templates/app/organization/edit.html.eex
<div class="container">

	<div class="row">
		<div class="col-md-12">
			<%= if @organization.action do %>
		    <div class="alert alert-danger">
		      <p>Oops, something went wrong! Please check the errors below.</p>
		    </div>
		  <% end %>

			<!-- Nav tabs -->
			<ul class="nav nav-tabs" role="tablist">
				<li role="presentation" class="active"><a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">Settings</a></li>
				<li role="presentation"><a href="#templates" aria-controls="templates" role="tab" data-toggle="tab">Templates</a></li>
				<li role="presentation"><a href="#advanced" aria-controls="advanced" role="tab" data-toggle="tab">Advanced</a></li>
				<li role="presentation"><a href="#api-token" aria-controls="api-token" role="tab" data-toggle="tab">API Token</a></li>
				<li role="presentation"><a href="#signing-key" aria-controls="signing-key" role="tab" data-toggle="tab">Public Signing Key</a></li>
				<li role="presentation"><a href="#data-cleanup" aria-controls="data-cleanup" role="tab" data-toggle="tab">Data Cleanup</a><li>
			</ul>

			<!-- Tab panes -->
			<div class="tab-content">
				<div role="tabpanel" class="tab-pane active" id="settings">
					<div class="panel-header">
					</div>
					<div class="panel-body">
						<div class="row">
							<div class="col-md-6">
								<%= form_for @organization, @action, [as: :organization, method: "put"], fn f -> %>

									<%= input f, :name %>
									<%= inputs_for f, :settings, fn s -> %>
										<fieldset>
											<legend>Roku</legend>
											<%= input s, :roku_api_key %>
										</fieldset>
										<fieldset>
											<legend>Apple</legend>
											<%= input s, :apple_app_shared_secret %>
											<%= checkbox_switch s, :use_apple_sandbox_environment, data: [toggle: "tooltip", placement: "top"], title: "Toggle Validation with Apple Sandbox Environment" %>
										</fieldset>
										<fieldset>
											<legend>Google</legend>
											<%= input s, :google_package_name %>
											<%= input s, :google_service_account %>
											<%= input s, :google_service_account_private_key, using: :textarea %>
										</fieldset>
										<fieldset>
											<legend>Amazon</legend>
											<%= input s, :amazon_shared_secret %>
											<%= checkbox_switch s, :amazon_use_sandbox, data: [toggle: "tooltip", placement: "top"], title: "Toggle Amazon RVS Sandbox" %>
										</fieldset>
										<fieldset>
											<legend>Review Mode</legend>

											<p>When apps are undergoing the submission process, it may be necessary
											 to allow access to your applications without requiring email verification
											  (ie. QA does not have access to the inbox of the email address they are using).
												In this case, you can put your Organization into "Review Mode" by checking the box below.</p>

											<%= checkbox_switch s, :in_review_mode, data: [toggle: "tooltip", placement: "top"], title: "Toggle Review Mode for Organization" %>

										</fieldset>
									<% end %>

									<div class="form-group">
										<%= submit "Save", class: "btn btn-primary" %>
									</div>
								<% end %>
							</div>
						</div>
					</div>
				</div>
				<div role="tabpanel" class="tab-pane" id="templates">
					<div class="panel-header">
					</div>
					<div class="panel-body">
						<p>The following templates for user-facing items are available for you to customize.</p>
						<%= form_for @organization, @action, [as: :organization, method: "put"], fn f -> %>
							<%= inputs_for f, :templates, fn t -> %>
								<%= input t, :device_connection_email_subject, using: :text_input %>
								<%= input t, :device_connection_email_html, using: :textarea, help: raw("Available fields: #{device_connection_email_template_fields()}") %>
								<%= input t, :device_connection_email_text, using: :textarea, help: raw("Available fields: #{device_connection_email_template_fields()}") %>
							<% end %>
							<div class="form-group">
								<%= submit "Save", class: "btn btn-primary" %>
							</div>
						<% end %>
					</div>
				</div>

				<div role="tabpanel" class="tab-pane" id="advanced">
					<div class="panel-header">
					</div>
					<div class="panel-body">
						<div class="row">
							<div class="col-md-6">
								<%= form_for @organization, @action, [as: :organization, method: "put"], fn f -> %>
									<p class="alert alert-warning">Warning: Updating the URN value can affect pending connections</p>
									<%= input f, :urn %>
									<div class="form-group">
										<%= submit "Save", class: "btn btn-primary" %>
									</div>
								<% end %>
							</div>
						</div>
					</div>
				</div>

				<div role="tabpanel" class="tab-pane" id="api-token">
					<div class="panel-header">
						<h4>Generate API Token</h4>
					</div>
					<div id="api-token-body"></div>
				</div>
				<div role="tabpanel" class="tab-pane" id="signing-key">
					<div class="panel-header">
						<h4>Download Public Signing Key</h4>
					</div>
					<div class="panel-body">
						<p>The Public Signing Key is used to verify the JWT that is generated upon successful verification of a Connection.</p>
						<%= button to: signing_key_path(@conn, :index), method: "get", class: "btn btn-default btn-sm" do %>
							<span class="glyphicon glyphicon-download-alt"></span>&nbsp;&nbsp;Download
						<% end %>
					</div>
				</div>
				<div role="tabpanel" class="tab-pane" id="data-cleanup">
					<div class="panel-header">
						<h4>Data Cleanup</h4>
					</div>
					<div id="data-cleanup-body"></div>
				</div>
			</div>
		</div>
	</div>
</div>

apps/front_end/lib/web/templates/app/organization/index.html.eex
<div class="container">
	<div class="row">
		<div class="col-lg-12">
			<ol class="breadcrumb">
				<li><%= link "Dashboard", to: dashboard_path(@conn, :index) %></li>
				<li><a href="<%= organization_path(@conn, :edit, @current_organization.urn) %>">Organization</a></li>
				<li class="active">Organizations</li>
			</ol>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<h3>Select an Organization</h3>
			<table class="table table-condensed table-hover">
				<thead>
					<tr>
						<th>Organization</th>
						<th>&nbsp;</th>
					</tr>
				</thead>
				<tbody>
					<%= for organization <- @organizations do %>
						<tr>
							<td><%= organization.name %></td>
							<td>
								<%= link "Switch", to: organization_path(@conn, :switch, organization.id), class: "btn btn-xs btn-info", role: "button" %>
							</td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>